// Generated by CoffeeScript 1.10.0
var TetoriMinoRed, TetorisObject, check, create, update,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

TetorisObject = (function() {
  function TetorisObject(args, width, height) {
    this.args = args;
    this.width = width;
    this.height = height;
    this.moveEnable = true;
  }

  return TetorisObject;

})();

update = function() {
  return true;
};

check = function() {
  return true;
};

create = function() {
  $('#field').append('<div class="blockElement"></div>');
  return true;
};

TetoriMinoRed = (function(superClass) {
  extend(TetoriMinoRed, superClass);

  function TetoriMinoRed(args) {
    create;
  }

  return TetoriMinoRed;

})(TetorisObject);
