// Generated by CoffeeScript 1.10.0
(function() {
  var TetorisObject, create, update;

  TetorisObject = (function() {
    function TetorisObject(args) {
      this.args = args;
    }

    return TetorisObject;

  })();

  update = function() {};

  create = function() {};

}).call(this);
