// Generated by CoffeeScript 1.10.0
var TetriminoBlockElement;

TetriminoBlockElement = (function() {
  var helloConsole;

  function TetriminoBlockElement(name, pTop, pLeft, color) {
    if (pTop == null) {
      pTop = 0;
    }
    if (pLeft == null) {
      pLeft = 0;
    }
    if (color == null) {
      color = "red";
    }
    this.pointTop = pTop;
    this.pointLeft = pLeft;
    this.myName = name;
    this.type = color;
    this.append();
    this.move(this.pointTop, this.pointLeft);
  }

  TetriminoBlockElement.prototype.append = function() {
    $("#field").append("<div class='falling_" + this.type + "' id='" + this.myName + "'></div>");
  };

  TetriminoBlockElement.prototype.move = function(deltaPointTop, deltaPointLeft) {
    var pointLeft, pointTop;
    if (deltaPointTop == null) {
      deltaPointTop = 0;
    }
    if (deltaPointLeft == null) {
      deltaPointLeft = 0;
    }
    pointTop = this.getTop("#" + this.myName);
    pointLeft = this.getLeft("#" + this.myName);
    $("#" + this.myName).css("top", pointTop + deltaPointTop);
    $("#" + this.myName).css("left", pointLeft + deltaPointLeft);
  };

  TetriminoBlockElement.prototype.moveAbolute = function(top, left) {
    $("#" + this.myName).css("top", pointTop + deltaPointTop);
    $("#" + this.myName).css("left", pointLeft + deltaPointLeft);
  };

  TetriminoBlockElement.prototype.getTop = function(selector, property) {
    if (property == null) {
      property = "top";
    }
    return parseInt($(selector).css("top").slice(0, -2));
  };

  TetriminoBlockElement.prototype.getLeft = function(selector, property) {
    if (property == null) {
      property = "left";
    }
    return parseInt($(selector).css("left").slice(0, -2));
  };

  TetriminoBlockElement.prototype["delete"] = function() {
    return $("#" + this.myName).remove();
  };

  helloConsole = function(str) {
    console.log("hello from " + str);
  };

  return TetriminoBlockElement;

})();
