// Generated by CoffeeScript 1.10.0
var TetriminoBlockElement;

TetriminoBlockElement = (function() {
  var helloConsole;

  function TetriminoBlockElement(name, pTop, pLeft, color) {
    if (pTop == null) {
      pTop = 0;
    }
    if (pLeft == null) {
      pLeft = 0;
    }
    if (color == null) {
      color = "red";
    }
    this.pointTop = pTop;
    this.pointLeft = pLeft;
    this.myName = name;
    this.type = color;
    this.me = "#" + this.myName;
    this.append();
    this.move(this.pointTop, this.pointLeft);
  }

  TetriminoBlockElement.prototype.append = function() {
    $("#field").append("<div class='falling_" + this.type + "' id='" + this.myName + "'></div>");
  };

  TetriminoBlockElement.prototype.move = function(deltaPointTop, deltaPointLeft) {
    var pointLeft, pointTop;
    if (deltaPointTop == null) {
      deltaPointTop = 0;
    }
    if (deltaPointLeft == null) {
      deltaPointLeft = 0;
    }
    pointTop = this.getTop(this.me);
    pointLeft = this.getLeft(this.me);
    $(this.me).css("top", pointTop + deltaPointTop);
    $(this.me).css("left", pointLeft + deltaPointLeft);
  };

  TetriminoBlockElement.prototype.moveAbsolute = function(top, left) {
    $(this.me).css("top", top);
    $(this.me).css("left", left);
  };

  TetriminoBlockElement.prototype.getTop = function(selector, property) {
    if (property == null) {
      property = "top";
    }
    return parseInt($(selector).css("top").slice(0, -2));
  };

  TetriminoBlockElement.prototype.getLeft = function(selector, property) {
    if (property == null) {
      property = "left";
    }
    return parseInt($(selector).css("left").slice(0, -2));
  };

  TetriminoBlockElement.prototype["delete"] = function() {
    return $(this.me).remove();
  };

  TetriminoBlockElement.prototype.judgeRight = function() {
    var pro;
    pro = this.getLeft(this.me) + 30;
    if (pro >= 600) {
      return false;
    } else {
      return true;
    }
  };

  TetriminoBlockElement.prototype.judgeLeft = function() {
    var pro;
    pro = this.getLeft(this.me) - 30;
    if (pro < 0) {
      return false;
    } else {
      return true;
    }
  };

  TetriminoBlockElement.prototype.judgeBottom = function() {
    var pro;
    pro = this.getTop(this.me) + 30;
    if (pro >= 600) {
      return false;
    } else {
      return true;
    }
  };

  TetriminoBlockElement.prototype.changeAttr = function() {
    return $(this.me).removeAttr("id");
  };

  helloConsole = function(str) {
    console.log("hello from " + str);
  };

  return TetriminoBlockElement;

})();
