// Generated by CoffeeScript 1.10.0
(function() {
  var move;

  move = function(direction, minus) {
    var fun;
    return $('.falling').each(fun = function() {
      var blockBottom, blockCSS, blockRight;
      blockCSS = parseInt($(this).css("" + direction).slice(0, -2));
      blockBottom = parseInt($(this).css("bottom").slice(0, -2));
      blockRight = parseInt($(this).css("right").slice(0, -2));
      if (minus === 1) {
        if (blockCSS < 500) {
          blockCSS += 30;
        }
      } else {
        if (blockCSS > 0) {
          blockCSS -= 30;
        }
      }
      return $(this).css("" + direction, blockCSS);
    });
  };

  $(window).on("keydown", function(e) {
    var bot;
    bot = $('#field').css("bottom");
    console.log(bot);
    switch (e.keyCode) {
      case 40:
        return move("top", 1);
      case 39:
        return move("left", 1);
      case 37:
        return move("left", -1);
    }
  });

}).call(this);
