// Generated by CoffeeScript 1.10.0
(function() {
  var blockTop, move;

  blockTop = 0;

  move = function() {
    var fun;
    blockTop += 10;
    return $('.falling').each(fun = function() {
      console.log(blockTop);
      return $(this).css("top", blockTop);
    });
  };

  $(document).on("click", '#button', function() {
    console.log("Hi");
    return move();
  });

}).call(this);
