// Generated by CoffeeScript 1.10.0

function move(direction, minus) {
  var fun;
  if (direction == null) {
    direction = "top";
  }
  if (minus == null) {
    minus = 1;
  }
  return $('.falling').each(fun = function() {
    var blockCSS;
    blockCSS = parseInt($(this).css("" + direction).slice(0, -2));
    if (minus === 1) {
      if (blockCSS < 600) {
        blockCSS += 30;
      }
    } else {
      if (blockCSS > 0) {
        blockCSS -= 30;
      }
    }
    console.log(blockCSS);
    return $(this).css("" + direction, blockCSS);
  });
};

$(window).on("keydown", function(e) {
  switch (e.keyCode) {
    case 40:
      return move();
    case 39:
      return move("left", 1);
    case 37:
      return move("left", -1);
    case 32:
      // console.log(Hi);
      return setInterval("move()", 1000);
  }
});
