// Generated by CoffeeScript 1.10.0
var blocks, test;

blocks = [];

test = 0;

$(document).on("ready", function() {
  return test = new TetriminoRed;
});

$(window).on("keydown", function(e) {
  if (e.keyCode === 40) {
    return test.move(30, 0);
  } else if (e.keyCode === 39) {
    return test.move(0, 30);
  } else if (e.keyCode === 37) {
    return test.move(0, -30);
  }
});
