// Generated by CoffeeScript 1.10.0
var block;

block = 0;

$(document).on("ready", function() {
  console.log("Hi.");
  return block = new TetriminoBlockElement;
});

$(window).on("keydown", function(e) {
  if (e.keyCode === 40) {
    return block.move(30, 0);
  } else if (e.keyCode === 39) {
    return block.move(0, 30);
  } else if (e.keyCode === 37) {
    return block.move(0, -30);
  }
});
