// Generated by CoffeeScript 1.10.0
var TetriminoBlockElement;

TetriminoBlockElement = (function() {
  var helloConole;

  function TetriminoBlockElement() {
    helloConole("by constructor");
    this.append();
  }

  TetriminoBlockElement.prototype.append = function() {
    helloConole("from @append");
    return $("#field").append("<div class='falling_red'></div>");
  };

  TetriminoBlockElement.prototype.move = function(deltaPointTop, deltaPointLeft) {
    var pointLeft, pointTop;
    if (deltaPointTop == null) {
      deltaPointTop = 0;
    }
    if (deltaPointLeft == null) {
      deltaPointLeft = 0;
    }
    pointTop = this.getTop(".falling_red");
    pointLeft = this.getLeft(".falling_red");
    $(".falling_red").css("top", pointTop + deltaPointTop);
    return $(".falling_red").css("left", pointLeft + deltaPointLeft);
  };

  TetriminoBlockElement.prototype.getTop = function(selector, property) {
    if (property == null) {
      property = "top";
    }
    return parseInt($(selector).css("top").slice(0, -2));
  };

  TetriminoBlockElement.prototype.getLeft = function(selector, property) {
    if (property == null) {
      property = "left";
    }
    return parseInt($(selector).css("left").slice(0, -2));
  };

  helloConole = function(str) {
    return console.log("hello from " + str);
  };

  return TetriminoBlockElement;

})();
