// Generated by CoffeeScript 1.10.0
var Tetrimino, TetriminoRed, idNumber,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

idNumber = 0;

Tetrimino = (function() {
  function Tetrimino(locate, type) {
    this.type = type;
    this.point = {
      top: 0,
      left: 0
    };
    this.blocks = [new TetriminoBlockElement("block" + (idNumber++), locate[0], locate[1], type), new TetriminoBlockElement("block" + (idNumber++), locate[2], locate[3], type), new TetriminoBlockElement("block" + (idNumber++), locate[4], locate[5], type), new TetriminoBlockElement("block" + (idNumber++), locate[6], locate[7], type)];
    this.deg = {
      "deg0": locate,
      "deg90": [0, 0, 0, 0, 0, 0, 0, 0],
      "deg180": [0, 0, 0, 0, 0, 0, 0, 0],
      "deg270": [0, 0, 0, 0, 0, 0, 0, 0]
    };
  }

  Tetrimino.prototype.move = function(deltaPointTop, deltaPointLeft) {
    var block, j, len, ref, results;
    this.point.top += deltaPointTop;
    this.point.left += deltaPointLeft;
    ref = this.blocks;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      block = ref[j];
      results.push(block.move(deltaPointTop, deltaPointLeft));
    }
    return results;
  };

  Tetrimino.prototype.rotate = function(deg) {
    var block, i, j, len, ref, results;
    ref = this.blocks;
    results = [];
    for (i = j = 0, len = ref.length; j < len; i = ++j) {
      block = ref[i];
      results.push(block.moveAbsolute(this.point.top + this.deg["deg" + deg][i * 2], this.point.left + this.deg["deg" + deg][i * 2 + 1]));
    }
    return results;
  };

  return Tetrimino;

})();

TetriminoRed = (function(superClass) {
  extend(TetriminoRed, superClass);

  function TetriminoRed() {
    TetriminoRed.__super__.constructor.call(this, [0, 0, 30, 0, 30, 30, 30, 60], "red");
    this.deg["deg90"] = [0, 30, 0, 60, 30, 30, 60, 30];
    this.deg["deg180"] = [30, 0, 30, 30, 30, 60, 60, 60];
    this.deg["deg270"] = [0, 30, 30, 30, 60, 0, 60, 30];
  }

  return TetriminoRed;

})(Tetrimino);
