// Generated by CoffeeScript 1.10.0
var Update, helloConole;

Update = (function() {
  function Update() {
    helloConole("by constructor");
  }

  Update.prototype.append = function() {
    helloConole("from @append");
    return $("#field").append("<div class='falling_red'></div>");
  };

  return Update;

})();

$(window).on("keydown", function(e) {
  var up;
  if (e.keyCode === 32) {
    helloConole("ShiftKeyDownEvent");
    up = new Update;
    return up.append();
  }
});

helloConole = function(str) {
  return console.log("hello from " + str);
};
